version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_DATABASE: mysql
      MYSQL_USER: axel
      MYSQL_PASSWORD: numerge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
